package zur.koeln.kickertool.uifxml.vm.wrapper;

public enum TournamentConfigFields {
	
	NUMBER_OF_TABLES, 
	NUMBER_OF_TABLES_DEFAULT,
	MATCHES_TO_WIN,
	MATCHES_TO_WIN_DEFAULT,
	GOALS_TO_WIN,
	GOALS_TO_WIN_DEFAULT,
	POINTS_TO_WIN,
	POINTS_TO_WIN_DEFAULT,
	POINTS_FOR_DRAW,
	POINTS_FOR_DRAW_DEFAULT,
	MINUTES_FOR_MATCH,
	MINUTES_FOR_MATCH_DEFAULT,
	RANDOM_ROUNDS_START,
	RANDOM_ROUNDS_START_DEFAULT
	
}
